Exception in thread Thread-994:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 99, in run
    inter = self.inter, verbose = self.verbose)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 279, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 33, in send
    sx = str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 341, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 105, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 205, in i2m
    return mac2str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in mac2str
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in <lambda>
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
ValueError: invalid literal for int() with base 16: '<incomplete>'

Exception in thread Thread-15130:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 99, in run
    inter = self.inter, verbose = self.verbose)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 279, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 33, in send
    sx = str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 341, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 105, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 205, in i2m
    return mac2str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in mac2str
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in <lambda>
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
ValueError: invalid literal for int() with base 16: '<incomplete>'

Exception in thread Thread-15134:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 99, in run
    inter = self.inter, verbose = self.verbose)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 279, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 33, in send
    sx = str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 341, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 105, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 205, in i2m
    return mac2str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in mac2str
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in <lambda>
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
ValueError: invalid literal for int() with base 16: '<incomplete>'

Exception in thread Thread-15138:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 99, in run
    inter = self.inter, verbose = self.verbose)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 279, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 33, in send
    sx = str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 341, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 105, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 205, in i2m
    return mac2str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in mac2str
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in <lambda>
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
ValueError: invalid literal for int() with base 16: '<incomplete>'

Exception in thread Thread-15142:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 99, in run
    inter = self.inter, verbose = self.verbose)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 279, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 33, in send
    sx = str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 341, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 105, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 205, in i2m
    return mac2str(x)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in mac2str
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 295, in <lambda>
    return "".join(map(lambda x: chr(int(x,16)), mac.split(":")))
ValueError: invalid literal for int() with base 16: '<incomplete>'

Exception in thread Thread-15137:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 50, in run
    count = self.count, timeout = self.timeout)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 610, in sniff
    p = s.recv()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 519, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

Exception in thread Thread-15136:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 50, in run
    count = self.count, timeout = self.timeout)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 610, in sniff
    p = s.recv()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 519, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

Exception in thread Thread-15143:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15145:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15147:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15149:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-44:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15151:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15153:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15154:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15157:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15159:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15161:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15163:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15165:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15167:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-49:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15169:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15171:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15173:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15175:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15177:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15179:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-15181:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/traffic.py", line 144, in run
    debug = self.debug)
  File "/home/radu/Ping/traffic.py", line 39, in __init__
    self.iface = iface if iface else ip_to_dev(ip)
NameError: global name 'ip' is not defined

Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/radu/Ping/main.py", line 63, in run
    write.add_value(db = self.db, tb = table, **host_dict)
  File "/home/radu/Ping/sql_lib.py", line 66, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

