Exception in thread decdc99plops001.bcdtravel.eu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 58, in run
    sql().add_value(db = self.db, tb = table, **host_dict)
  File "/root/netmonpy/Ping/sql_lib.py", line 62, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread nss.contabo.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./run.py", line 103, in run
    print 'Started thread %s' %i[hd['Name']]
TypeError: 'monitor' object does not support indexing

Exception in thread client.bigtelecom.ru:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./run.py", line 103, in run
    print 'Started thread %s' %i[hd['Name']]
TypeError: 'monitor' object does not support indexing

Exception in thread rev.cloud.scaleway.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread decdc99plops001.bcdtravel.eu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

Exception in thread mazda.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread a062.g.tyo1.static.cnode.io:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread clients.yourserver.de:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread client.bigtelecom.ru:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread amazon.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread global2.dns:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Temporary failure in name resolution

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./run.py", line 103, in run
    print 'Started thread %s' %i[hd['Name']]
TypeError: 'monitor' object does not support indexing

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./run.py", line 103, in run
    print 'Started thread %s' %i[hd['Name']]
TypeError: 'monitor' object does not support indexing

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./run.py", line 103, in run
    print 'Started thread %s' %i[hd['Name']]
TypeError: 'monitor' object does not support indexing

Exception in thread global.dns:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 58, in run
    sql().add_value(db = self.db, tb = table, **host_dict)
  File "/root/netmonpy/Ping/sql_lib.py", line 62, in add_value
    self.cursor.execute(cmd)
IntegrityError: UNIQUE constraint failed: global_dns.Time

