Exception in thread a062.g.tyo1.static.cnode.io:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 84, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

Exception in thread cr02.interlan.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

Exception in thread decdc99plops001.bcdtravel.eu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 58, in run
    sql().add_value(db = self.db, tb = table, **host_dict)
  File "/root/netmonpy/Ping/sql_lib.py", line 62, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread Thread-743199:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/traffic.py", line 204, in run
    seq_dict[int(i[ICMP].seq)] = i.time
TypeError: int() argument must be a string or a number, not 'NoneType'

Exception in thread google2.dns.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 58, in run
    sql().add_value(db = self.db, tb = table, **host_dict)
  File "/root/netmonpy/Ping/sql_lib.py", line 62, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread rev.poneytelecom.eu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread protv.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 113] No route to host

Exception in thread clients.yourserver.de:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread svr.mistermoneybrasil.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread mx.gznleasing.ru:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 113] No route to host

Exception in thread wikipedia.org:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread nss.contabo.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread client.bigtelecom.ru:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread Vodafone.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread mazda.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread decdc99plops001.bcdtravel.eu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread amazon.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread anm.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread mail.ru.yangming.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread m247europa.peer.interlan.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 84, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

Exception in thread Thread-1014879:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/traffic.py", line 204, in run
    seq_dict[int(i[ICMP].seq)] = i.time
TypeError: int() argument must be a string or a number, not 'NoneType'

Exception in thread oath.peer.interlan.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 58, in run
    sql().add_value(db = self.db, tb = table, **host_dict)
  File "/root/netmonpy/Ping/sql_lib.py", line 62, in add_value
    self.cursor.execute(cmd)
OperationalError: near ")": syntax error

Exception in thread google.peer.interlan.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out

Exception in thread google3.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

Exception in thread bbc.uk:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 84, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 16, in send_mail
    server = smtplib.SMTP_SSL('mail.vhsmail.vodafone.com', 465)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

Exception in thread google2.ro:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/netmonpy/Ping/main.py", line 78, in run
    %(self.name, self.host, ctime(host_dict['Time'])))
  File "/root/netmonpy/Ping/mail.py", line 30, in send_mail
    server.quit()
  File "/usr/lib/python2.7/smtplib.py", line 772, in quit
    res = self.docmd("quit")
  File "/usr/lib/python2.7/smtplib.py", line 394, in docmd
    return self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: [Errno 104] Connection reset by peer

